/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mcz' at '31.03.17 11:45' with Gradle 3.0
 *
 * @author mcz, @date 31.03.17 11:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
